language: rust
os:
  - linux
  - osx
before_install:
  - sudo add-apt-repository -y ppa:kalakris/cmake
  - sudo apt-get update -qq
install:
  - sudo apt-get install cmake libXxf86vm-dev libxinerama-dev libxcursor-dev
notifications:
  irc:
    nick: opengl-practice
    channels:
      - irc.uriirc.org:16667#hyeon
    template:
      - "#%{build_number} %{result}, %{build_url}"
    skip_join: true
