language: rust

sudo: false
addons:
  apt:
    sources: kalakris-cmake
    packages: cmake libXxf86vm-dev libxinerama-dev libxcursor-dev

notifications:
  irc:
    nick: opengl-practice
    channels: 'ircs://irc.uriirc.org:16664#hyeon'
    template: '#%{build_number} %{result}, %{build_url}'
    skip_join: true
