[package]
name = "encode-practice"
version = "0.1.0"
authors = ["Hyeon Kim <simnalamburt@gmail.com>"]
edition = "2018"

[dependencies]
obj-rs = "0.7"
serde = "1"
time = "0.3"
bincode = "1"
serde_json = "1"
