on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cargo build
      - run: cargo test
      - run: cargo clippy --all --no-deps -- -D warnings
      - run: cargo fmt --all -- --check

  other:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - run: cargo build
